#!/bin/bash

IMA="ami-04a81a99f5ec58529"
Instance_type="t2.micro"
keys="13th_july_2024_personalized_greetings"
sec_group="launch-wizard-5"
Intance_name=$1

aws ec2 run-instances \
--image-id $IMA \
--instance-type $Instance_type \
--key-name $keys \
--security-groups $sec_group \
--tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$1}]"
